# Generated by Django 5.0.2 on 2024-02-24 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Сфера бизнеса')),
            ],
            options={
                'verbose_name': 'Тип бизнеса',
                'verbose_name_plural': 'Типы бизнеса',
            },
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.businesstype', verbose_name='Тип бизнеса')),
            ],
            options={
                'verbose_name': 'Категория бизнеса',
                'verbose_name_plural': 'Категории бизнеса',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=256, null=True, verbose_name='Вопрос')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.businesscategory', verbose_name='Категория бизнеса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=256, null=True, verbose_name='Варианты ответов')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
